heat_template_version: 2016-10-14

description: >
  https://docs.openstack.org/heat/newton/template_guide/basic_resources.html
  digest
  get_attr
  get_file
  get_param
  get_resource
  list_join
  map_merge
  map_replace
  repeat
  resource_facade
  str_replace
  str_split
  yaql
  if
  equals
  get_param
  not
  and
  or

parameters:
  key_name:
    type: string
    default: HEAT_KEY
    description: Name of an existing (on the csc) key pair to use for the instance
  mount_point:
    type: string
    default: '/dev/vdb'
    description: whatever

resources:

        
# sudo mkfs.ext4 ${some_input}
# sudo mkdir -p /media/volume
# sudo mount ${some_input} /media/volume
# sudo mkdir -p /media/volume/IT_WORKED && sudo chown -R $USER /media/volume/IT_WORKED

  # this creates a new volume
  new_vol:
    type: OS::Cinder::Volume
    properties:
      size: 100

  # this create a floating ip 
  floating_ip:
    type: OS::Nova::FloatingIP
    properties:
      pool: public

  # this associates security groups to the port
  instance_port:
    type: OS::Neutron::Port
    properties:
      network: project_2000774
      security_groups:
        - default
        - SSH
        - Jupyter

  # this creates a key-pair
  #my_key:
  #  type: OS::Nova::KeyPair
  #  properties:
  #    save_private_key: true
  #    name: my_key  

  default_instance:
    # this creates the actual instance
    type: OS::Nova::Server
    properties:
      key_name: { get_param: key_name }
      image: Ubuntu-16.04
      flavor: standard.small
      networks:
        - port: { get_resource: instance_port }
#        - network: private
#below script exectus after startup
#      user_data:
#        str_replace:
#          template: |
#            #!/bin/bash
#            echo "$FOO"
#          params:
#            FOO: { get_attr: [ my_key, private_key ] }
      user_data_format: RAW
      user_data:
        # https://docs.openstack.org/heat/newton/template_guide/hot_spec.html#str-replace
        # https://webcache.googleusercontent.com/search?q=cache:IVrJbDeZ344J:https://www.cowley.tech/blog/2015/05/05/identify-and-mounting-cinder-volumes-in-openstack-heat/+&cd=1&hl=en&ct=clnk&gl=fi&client=safari
        str_replace:
          template: |
            #cloud-config
            write_files:
              - content: |
                  #!/bin/bash
                  voldata_id="%voldata_id%"
                  voldata_dev="/dev/disk/by-id/virtio-$(echo ${voldata_id} | cut -c -20)"
                  mkfs.ext4 ${voldata_dev}               
                  mkdir -p /media/volume
                  mount voldata_dev /media/volume
                  mkdir -p /media/volume1
                  voldata_id1="%voldata_id1%"
                  voldata_dev1="/dev/disk/by-id/virtio-$(echo ${voldata_id1} | cut -c -20)"
                  mount voldata_dev1 /media/volume1
                path: /tmp/format-disks
                permissions: '0700'
            runcmd:
              - /tmp/format-disks            
          params:
            "%voldata_id%": { get_resource: new_vol }
            "%voldata_id1%": 60cfa2f8-ae90-4edb-a7a0-0b873851b8c0


  # this attaches newly created volumes to the instance. Make sure that volume_attachment things are called differently
  volume_attachment_new:
    type: OS::Cinder::VolumeAttachment
    properties:
      volume_id: { get_resource: new_vol }
      instance_uuid: { get_resource: default_instance }

  volume_attachment_old:
    type: OS::Cinder::VolumeAttachment
    properties:
      volume_id: 60cfa2f8-ae90-4edb-a7a0-0b873851b8c0
      instance_uuid: { get_resource: default_instance }
#      mountpoint: /dev/vdc # mountpoint does not work. It assigns it at random

  
  association:
    # this associates floating ip with the created instance
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_resource: floating_ip }
      server_id: { get_resource: default_instance }

outputs:
#  private_key: 
#    description: Private key
#    value: { get_attr: [ my_key, private_key ] }
  instance_ip:
    description: Floating IP to be used for ssh'ing to the box
    value: { get_attr: [default_instance, networks, project_2000774, 1] }

